version: "3"
services:
  server:
    build: .
    command: server.js
    ports:
      - 8080:8080
    depends_on:
      - redis
    env_file:
      - .env
  worker:
    build: .
    command: worker.js
    depends_on:
      - redis
    env_file:
      - .env
  redis:
    image: redis
