version: "2.4"
services:
  server:
    build: .
    command: server.js
    ports:
      - 8080:8080
    depends_on:
      - redis
    env_file:
      - .env
  worker:
    build: .
    command: worker.js
    depends_on:
      - redis
    env_file:
      - .env
    cap_add:
      - SYS_ADMIN
  redis:
    image: redis
